// Create our global collection of **Curses**.
var curseData = [
		{title:"asshole",pos:["noun"],definition:""},
		{title:"bimmy",pos:["noun"],definition:""},
		{title:"bitch",pos:["noun","verb"],definition:""},
		{title:"ass clown",pos:["noun"],definition:""},
		{title:"ballsack",pos:["noun"],definition:""},
		{title:"bag o' dicks",pos:["noun"],definition:""},
		{title:"bangster",pos:["noun"],definition:""},
		{title:"beat off",pos:["verb"],definition:""},
		{title:"blow job",pos:["noun"],definition:""},
		{title:"boink",pos:["verb"],definition:""},
		{title:"boner",pos:["noun"],definition:""},
		{title:"brownhole",pos:["noun"],definition:""},
		{title:"brownie",pos:["noun"],definition:""},
		{title:"brownfinger",pos:["noun","verb"],definition:""},
		{title:"bucksnort",pos:["verb"],definition:""},
		{title:"buddery",pos:["adjective"],definition:""},
		{title:"bugger",pos:["noun"],definition:""},
		{title:"bulldyke",pos:["noun","verb"],definition:""},
		{title:"bullshit",pos:["noun","verb"],definition:""},
		{title:"bumble fuck",pos:["verb","noun"],definition:""},
		{title:"bunghole",pos:["noun"],definition:""},
		{title:"butt fuck",pos:["noun","verb"],definition:""},
		{title:"sharf",pos:["noun","verb"],definition:""},
		{title:"cock",pos:["noun"],definition:""},
		{title:"cunt",pos:["noun"],definition:""},
		{title:"cum dumpster",pos:["noun"],definition:""}
];